<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<RootNamespace>BlackHoleRayTracer</RootNamespace>
		<AssemblyName>BlackHoleRayTracer</AssemblyName>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<LangVersion>latest</LangVersion>
		<InvariantGlobalization>true</InvariantGlobalization>
		<ServerGarbageCollection>true</ServerGarbageCollection>
		<ConcurrentGarbageCollection>false</ConcurrentGarbageCollection>
		<TieredPGO>true</TieredPGO>
		<TieredCompilationQuickJit>false</TieredCompilationQuickJit>
		<TieredCompilationQuickJitForLoops>false</TieredCompilationQuickJitForLoops>
		<Optimize>true</Optimize>
		<DebugType>none</DebugType>
		<DebugSymbols>false</DebugSymbols>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="ILGPU" Version="1.5.3" />
		<PackageReference Include="SkiaSharp" Version="4.151.1" />
	</ItemGroup>

</Project>